### ISSUE TITLE
serial speeds

### ISSUE THREAD

**Issue by dschil138** [ripred/ButtonGestures#2]
I noticed that in the basic use example, you used Serial.begin(2000000), while in the register example, you used Serial.begin(115200).

I was just wondering what the reason was, and if there is a suggested speed you think is best to use with this library?

This isn't really an Issue I just wasn't sure how else to ask

**Comment by ripred** [comment]
That was just a failure on my part to be consistent.  Thanks for pointing that out.  I will edit the basic use example to use 115200 as well.

All the Best
